#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2020, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#
#

- name: "Create SSH config for the Monitor"
  gather_facts: false
  hosts: localhost
  vars_files:
    - /tmp/ansible-vars.yml

  tasks:

    - name: "Discover our zeppelin node"
      os_server_info:
        cloud:  "{{ cloudname }}"
        server: "{{ deployname }}-zeppelin"
      register:
        zeppelinnodes


    - name: "Generate Ansible SSH config"
      template:
        src:  "templates/ssh-monitor.j2"
        dest: "/tmp/aglais-monitor-config"
        mode: 'u=rw,g=,o='


- hosts: monitor
  gather_facts: false
  tasks:
    - name: "Deploy ssh file to monitor"
      become: true
      copy:
        src:  /tmp/aglais-monitor-config
        dest: "/home/{{ hostvars[inventory_hostname].login }}/.ssh/config"
        owner: root
        group: root
        mode:  u=rw,g=r,o=r


