---
- hosts: monitor
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - alertmanager

- hosts: masters:workers
  become: true
  roles:
    - prometheus_node_exporter

- hosts: monitor
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus

- hosts: monitor
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - grafana
